# Generated by Django 5.2.9 on 2026-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='facilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('university', 'name')},
        ),
    ]
