# Generated by Django 5.2.9 on 2026-06-13 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_building_facilities_building_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrar'),
        ),
        migrations.AddField(
            model_name='building',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده توسط ادمین'),
        ),
    ]
