# Generated by Django 5.2.9 on 2026-06-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0003_building_created_by_building_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='approved by admin'),
        ),
    ]
